export { default as clinicsCornering } from './clinics-cornering-img.jpg'
export { default as clinicsDrops } from './clinics-drops-img.jpg'
export { default as clinicsFundamentals } from './clinics-funadmentals-img.jpg'
export { default as clinicsJumping } from './clinics-jumping-img.jpg'
export { default as clinicsManual } from './clinics-manuals-img.png'
export { default as clinicsTechnicalClimbing } from './clinics-technical-climbing-img.jpg'
export { default as servicesOnlineCoaching } from './services-online-coaching-img.jpg'
export { default as servicesPrivateCoaching } from './services-private-coaching-img.jpg'
export { default as servicesSmallGroupCoaching } from './services-small-group-coaching-img.jpg'

